set -g @plugin 'dracula/tmux'

set -g @dracula-plugins 'network-vpn time'
set -g @dracula-network-vpn-label "󰌘 "
set -g @dracula-network-vpn-colors "gray white"
set -g @dracula-time-colors "dark_purple white"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind r source-file ~/.tmux.conf
set -g base-index 1
set -g renumber-windows on
set -s escape-time 0

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# custom key-bindings
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

run '~/.tmux/plugins/tpm/tpm'

