set -g @plugin 'dracula/tmux'

set -g @dracula-plugins 'network-vpn'
set -g @dracula-show-left-icon "#S"
set -g @dracula-network-vpn-label "󰌘 "
set -g @dracula-network-vpn-colors "gray white"

set -g @dracula-colors "
white='#e0def4'
gray='#26233a'
dark_gray='#191724'
light_purple='#c4a7e7'
dark_purple='#191724'
cyan='#9ccfd8'
green='#a6e3a1'
orange='#ea9a97'
red='#eb6f92'
pink='#f5c2e7'
yellow='#f6c177'
"

# set options
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

set -a terminal-features "tmux-256color:RGB" # true color support
set -g base-index 1 # index windows from 1
set -g renumber-windows on # renumber windows when one is closed
set -s escape-time 0 # escape time for faster key sequences
set -g mode-keys vi # vim-like key bindings in copy mode
set -g focus-events on # focus events for better terminal integration
set -g mouse on

# key-bindings
bind r source-file ~/.tmux.conf

# copy text on mouse drag end without exiting copy mode
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection
bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection

## pane management
bind = split-window -h -l "37%" -c "#{pane_current_path}"
bind - split-window -v -l "25%" -c "#{pane_current_path}"
unbind '"'
unbind %

## vim-like pane switching
bind -r ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 5

# popup windows
bind g popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"
bind p popup -d "#{pane_current_path}" -w 90% -h 90% -E ""

# silence monitor
bind m set-window-option monitor-silence 5 \; display-message "Silence Monitor: ON (5s)"
bind M set-window-option monitor-silence 0 \; display-message "Silence Monitor: OFF"

run '~/.tmux/plugins/tpm/tpm'

