set -g @plugin 'dracula/tmux'

set -g prefix C-a
unbind C-b
bind C-a send-prefix

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

run '~/.tmux/plugins/tpm/tpm'

